
  0%|                                                                                                                                                         | 0/10000 [00:00<?, ?it/s]/home/wenhan/anaconda3/envs/llava_env/lib/python3.10/site-packages/torch/nn/parallel/_functions.py:68: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
  warnings.warn('Was asked to gather along dimension 0, but all '
Traceback (most recent call last):
  File "/home/wenhan/Projects/LISA/model/llava_new/LLaVA/llava/train/train.py", line 1187, in <module>
    train()
  File "/home/wenhan/Projects/LISA/model/llava_new/LLaVA/llava/train/train.py", line 1143, in train
    trainer.train()
  File "/home/wenhan/anaconda3/envs/llava_env/lib/python3.10/site-packages/transformers/trainer.py", line 1539, in train
    return inner_training_loop(
  File "/home/wenhan/anaconda3/envs/llava_env/lib/python3.10/site-packages/transformers/trainer.py", line 1869, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/home/wenhan/anaconda3/envs/llava_env/lib/python3.10/site-packages/transformers/trainer.py", line 2772, in training_step
    loss = self.compute_loss(model, inputs)
  File "/home/wenhan/anaconda3/envs/llava_env/lib/python3.10/site-packages/transformers/trainer.py", line 2795, in compute_loss
    outputs = model(**inputs)
  File "/home/wenhan/anaconda3/envs/llava_env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/wenhan/anaconda3/envs/llava_env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/wenhan/anaconda3/envs/llava_env/lib/python3.10/site-packages/torch/nn/parallel/data_parallel.py", line 186, in forward
    return self.gather(outputs, self.output_device)
  File "/home/wenhan/anaconda3/envs/llava_env/lib/python3.10/site-packages/torch/nn/parallel/data_parallel.py", line 203, in gather
    return gather(outputs, output_device, dim=self.dim)
  File "/home/wenhan/anaconda3/envs/llava_env/lib/python3.10/site-packages/torch/nn/parallel/scatter_gather.py", line 105, in gather
    res = gather_map(outputs)
  File "/home/wenhan/anaconda3/envs/llava_env/lib/python3.10/site-packages/torch/nn/parallel/scatter_gather.py", line 96, in gather_map
    return type(out)((k, gather_map([d[k] for d in outputs]))
  File "<string>", line 8, in __init__
  File "/home/wenhan/anaconda3/envs/llava_env/lib/python3.10/site-packages/transformers/utils/generic.py", line 360, in __post_init__
    for idx, element in enumerate(iterator):
  File "/home/wenhan/anaconda3/envs/llava_env/lib/python3.10/site-packages/torch/nn/parallel/scatter_gather.py", line 96, in <genexpr>
    return type(out)((k, gather_map([d[k] for d in outputs]))
  File "/home/wenhan/anaconda3/envs/llava_env/lib/python3.10/site-packages/torch/nn/parallel/scatter_gather.py", line 90, in gather_map
    return Gather.apply(target_device, dim, *outputs)
  File "/home/wenhan/anaconda3/envs/llava_env/lib/python3.10/site-packages/torch/autograd/function.py", line 539, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/home/wenhan/anaconda3/envs/llava_env/lib/python3.10/site-packages/torch/nn/parallel/_functions.py", line 75, in forward
    return comm.gather(inputs, ctx.dim, ctx.target_device)
  File "/home/wenhan/anaconda3/envs/llava_env/lib/python3.10/site-packages/torch/nn/parallel/comm.py", line 231, in gather
    return torch._C._gather(tensors, dim, destination)
RuntimeError: Input tensor at index 1 has invalid shape [4, 440, 50266], but expected [4, 512, 50266]